### ISSUE TITLE
Bank Bug - Item Stacks

### ISSUE THREAD

**Issue by TempCC2** [CyberConnects2/R1Alpha-Tracker#13]
Depositing a single of a stackable item, ie Magnolia Miso or Aromatic Grass, exiting the bank, then coming back later and trying to add to the stack erases the initial item. This cannot be circumvented by withdrawing the single item stack first; whenever it next hits a stack of the same item, even if it's still only one, it will disappear.

**Comment by CyberConnects2** [comment]
Can't reproduce the error, assuming working as intended
